version: "3.9"

services:
  app:
    build: .
    container_name: blog-app
    restart: always
    expose:
      - "3000"
    env_file:
      - .env
    depends_on:
      - db
    environment:
      DATABASE_URL: postgres://${PG_USER}:${PG_PASSWORD}@db:5432/${PG_DATABASE}

  db:
    image: postgres:15
    container_name: blog-db
    restart: always
    environment:
      POSTGRES_USER: ${PG_USER}
      POSTGRES_PASSWORD: ${PG_PASSWORD}
      POSTGRES_DB: ${PG_DATABASE}
    volumes:
      - db_data:/var/lib/postgresql/data

volumes:
  db_data:
