services:
  blog-app:
    build: .
    container_name: blog-app
    restart: always
    depends_on:
      - blog-db
    env_file:
      - .env
    expose:
      - "3000"   # expose to other containers, no need for 3002 mapping anymore
    networks:
      - blog-net
      - caddy

  blog-db:
    image: postgres:15
    container_name: blog-db
    restart: always
    environment:
      - POSTGRES_USER=${PG_USER}
      - POSTGRES_PASSWORD=${PG_PASSWORD}
      - POSTGRES_DB=${PG_DATABASE}
    volumes:
      - blog-data:/var/lib/postgresql/data
    networks:
      - blog-net

networks:
  blog-net:
  caddy:
    external: true

volumes:
  blog-data:
