version: "3.8"

services:
  blog-app:
    build: .
    container_name: blog-app
    restart: always
    depends_on:
      - blog-db
    environment:
      - DATABASE_URL=postgresql://${PG_USER}:${PG_PASSWORD}@blog-db:5432/${PG_DATABASE}
    ports:
      - "3002:3000"   # maps host:container
    networks:
      - blog-net

  blog-db:
    image: postgres:15
    container_name: blog-db
    restart: always
    environment:
      - POSTGRES_USER=${PG_USER}
      - POSTGRES_PASSWORD=${PG_PASSWORD}
      - POSTGRES_DB=${PG_DATABASE}
    volumes:
      - blog-data:/var/lib/postgresql/data
    networks:
      - blog-net

networks:
  blog-net:

volumes:
  blog-data:
